### ISSUE TITLE
cosyvoice-300m-sft deploy error

### ISSUE THREAD

**Issue by F5Psyche** [gpustack/gpustack#2205]
GPUStack version：v0.6.1 (a6f90c0)

I have executed 'pip install PEFT'
cuda:7 device VRAM 24G NO USE

![Image](https://github.com/user-attachments/assets/ec7bcb85-a40f-472f-8b07-b657ecc943f3)

How can I solve the error as shown in the picture

**Comment by gitlawr** [comment]
It's an OOM error. Can you show the `nvidia-smi` output when the error occurs?

**Comment by F5Psyche** [comment]
deploy again. "watch -n 0.1 nvidia-smi", cuda:7 no change
![Image](https://github.com/user-attachments/assets/3f7f52b3-26a1-4549-a618-a71301a95b16)

**Comment by gitlawr** [comment]
Related to https://github.com/gpustack/gpustack/issues/2078, which should be fixed in GPUStack v0.6.2 with vox-box v0.0.15. You can upgrade GPUStack to v0.6.2, or specify `v0.0.15` in `model configuration -> advanced -> backend version`.

**Comment by F5Psyche** [comment]
install  vox-box v0.0.15 faild

![Image](https://github.com/user-attachments/assets/74cbd29b-e259-4d25-99be-fd0cb9fd23bc)

**Comment by gitlawr** [comment]
Can you provide GPUStack logs from `/var/log/gpustack.log`(script installation) or container logs(docker installation)

**Comment by F5Psyche** [comment]
Successfully installed using `pip install vox-box==0.0.15`,  During deployment, installing vox box v0.0.15 using pipx will still occur，pipx error

![Image](https://github.com/user-attachments/assets/dd5e4d68-a44f-4566-b500-e39c17aaf0bb)

![Image](https://github.com/user-attachments/assets/3b10db48-6668-40fa-9632-7202ffd7cbb9)

**Comment by gitlawr** [comment]
> Can you provide GPUStack logs from `/var/log/gpustack.log`(script installation) or container logs(docker installation)

Detailed pipx installation logs is available in GPUStack worker logs. Can you provide relevant logs according to your installation method?

**Comment by F5Psyche** [comment]
Upgrading vox-box `pip install vox-box==0.0.15` without specifying backend version has resolved the issue, thanks

**Comment by F5Psyche** [comment]
> > Can you provide GPUStack logs from `/var/log/gpustack.log`(script installation) or container logs(docker installation)
> 
> Detailed pipx installation logs is available in GPUStack worker logs. Can you provide relevant logs according to your installation method?

![Image](https://github.com/user-attachments/assets/3c54e07a-37d8-4466-9da1-97942bcbb891)

**Comment by gitlawr** [comment]
It seems to be a networking issue. A related enhancement: https://github.com/gpustack/gpustack/issues/1988

**Comment by F5Psyche** [comment]
> 这似乎是网络问题。相关增强功能：[#1988](https://github.com/gpustack/gpustack/issues/1988)

Does the current version support configuring download sources? Do I need to wait for the new version to support it?

**Comment by gitlawr** [comment]
You can use whatever way you prefer to install as long as you link the executable properly. See https://docs.gpustack.ai/latest/user-guide/pinned-backend-versions/#manual-installation-of-pinned-backend-versions

**Comment by F5Psyche** [comment]
thanks
